
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 28 17:58:45 CET 2014
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.*;

/** CUP v0.10k generated parser.
  * @version Fri Feb 28 17:58:45 CET 2014
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\056\000\002\002\004\000\002\003\003\000\002\003" +
    "\003\000\002\004\006\000\002\004\006\000\002\004\006" +
    "\000\002\005\006\000\002\005\006\000\002\005\006\000" +
    "\002\015\003\000\002\015\004\000\002\014\003\000\002" +
    "\014\003\000\002\016\006\000\002\016\006\000\002\017" +
    "\006\000\002\017\006\000\002\017\006\000\002\021\003" +
    "\000\002\021\004\000\002\020\006\000\002\020\006\000" +
    "\002\006\004\000\002\007\003\000\002\010\007\000\002" +
    "\010\007\000\002\010\007\000\002\010\007\000\002\011" +
    "\004\000\002\012\003\000\002\013\007\000\002\024\004" +
    "\000\002\025\014\000\002\025\007\000\002\022\004\000" +
    "\002\023\007\000\002\023\014\000\002\026\004\000\002" +
    "\027\014\000\002\027\014\000\002\027\007\000\002\027" +
    "\007\000\002\031\003\000\002\031\003\000\002\031\003" +
    "\000\002\030\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\204\000\006\003\005\004\004\001\002\000\010\003" +
    "\013\020\011\021\016\001\002\000\004\002\uffff\001\002" +
    "\000\004\002\010\001\002\000\004\002\000\001\002\000" +
    "\004\002\001\001\002\000\004\025\201\001\002\000\006" +
    "\003\176\006\027\001\002\000\004\006\027\001\002\000" +
    "\004\024\025\001\002\000\004\024\uffea\001\002\000\004" +
    "\025\017\001\002\000\004\023\020\001\002\000\006\003" +
    "\022\031\021\001\002\000\004\023\024\001\002\000\004" +
    "\023\023\001\002\000\004\024\uffe6\001\002\000\004\024" +
    "\uffe7\001\002\000\006\003\uffeb\006\uffeb\001\002\000\004" +
    "\005\174\001\002\000\006\003\032\021\034\001\002\000" +
    "\010\003\171\010\042\012\044\001\002\000\004\024\167" +
    "\001\002\000\006\010\042\012\044\001\002\000\004\024" +
    "\uffe4\001\002\000\004\025\035\001\002\000\004\023\036" +
    "\001\002\000\004\031\037\001\002\000\004\023\040\001" +
    "\002\000\004\024\uffe3\001\002\000\010\007\165\010\042" +
    "\012\044\001\002\000\004\021\146\001\002\000\010\007" +
    "\ufff8\010\ufff8\012\ufff8\001\002\000\010\003\050\017\047" +
    "\021\052\001\002\000\010\007\ufff5\010\ufff5\012\ufff5\001" +
    "\002\000\010\007\ufff6\010\ufff6\012\ufff6\001\002\000\004" +
    "\025\140\001\002\000\004\014\054\001\002\000\004\024" +
    "\135\001\002\000\004\025\124\001\002\000\006\003\055" +
    "\014\054\001\002\000\006\021\066\022\063\001\002\000" +
    "\004\013\062\001\002\000\006\013\060\014\054\001\002" +
    "\000\006\013\uffef\014\uffef\001\002\000\010\007\ufff2\010" +
    "\ufff2\012\ufff2\001\002\000\006\013\uffee\014\uffee\001\002" +
    "\000\010\007\ufff0\010\ufff0\012\ufff0\001\002\000\004\025" +
    "\111\001\002\000\006\024\107\026\106\001\002\000\004" +
    "\031\103\001\002\000\004\025\067\001\002\000\004\023" +
    "\070\001\002\000\010\027\073\030\071\031\072\001\002" +
    "\000\004\023\uffd6\001\002\000\004\023\uffd7\001\002\000" +
    "\004\023\uffd5\001\002\000\004\023\075\001\002\000\010" +
    "\016\076\024\uffd8\026\uffd8\001\002\000\004\025\077\001" +
    "\002\000\004\023\100\001\002\000\010\027\073\030\071" +
    "\031\072\001\002\000\004\023\102\001\002\000\006\024" +
    "\uffda\026\uffda\001\002\000\006\011\uffd4\015\uffd4\001\002" +
    "\000\004\015\105\001\002\000\006\013\uffed\014\uffed\001" +
    "\002\000\004\024\110\001\002\000\004\031\uffdc\001\002" +
    "\000\006\013\uffec\014\uffec\001\002\000\004\023\112\001" +
    "\002\000\010\027\073\030\071\031\113\001\002\000\004" +
    "\023\uffd7\001\002\000\004\023\115\001\002\000\006\024" +
    "\uffd9\026\uffd9\001\002\000\004\016\117\001\002\000\004" +
    "\025\120\001\002\000\004\023\121\001\002\000\010\027" +
    "\073\030\071\031\072\001\002\000\004\023\123\001\002" +
    "\000\006\024\uffdb\026\uffdb\001\002\000\004\023\125\001" +
    "\002\000\004\031\126\001\002\000\004\023\127\001\002" +
    "\000\004\017\130\001\002\000\004\025\131\001\002\000" +
    "\004\023\132\001\002\000\004\027\133\001\002\000\004" +
    "\023\134\001\002\000\004\024\uffdd\001\002\000\006\003" +
    "\uffdf\014\uffdf\001\002\000\006\013\137\014\054\001\002" +
    "\000\010\007\ufff1\010\ufff1\012\ufff1\001\002\000\004\023" +
    "\141\001\002\000\004\027\142\001\002\000\004\023\143" +
    "\001\002\000\004\024\uffde\001\002\000\006\024\163\026" +
    "\162\001\002\000\004\031\103\001\002\000\004\025\147" +
    "\001\002\000\004\023\150\001\002\000\004\031\151\001" +
    "\002\000\004\023\152\001\002\000\010\016\153\024\uffe0" +
    "\026\uffe0\001\002\000\004\025\154\001\002\000\004\023" +
    "\155\001\002\000\010\027\073\030\071\031\072\001\002" +
    "\000\004\023\157\001\002\000\006\024\uffe1\026\uffe1\001" +
    "\002\000\004\011\161\001\002\000\010\007\ufff4\010\ufff4" +
    "\012\ufff4\001\002\000\004\024\164\001\002\000\004\031" +
    "\uffe2\001\002\000\010\007\ufff3\010\ufff3\012\ufff3\001\002" +
    "\000\004\005\ufffa\001\002\000\010\007\ufff7\010\ufff7\012" +
    "\ufff7\001\002\000\010\003\uffe5\010\uffe5\012\uffe5\001\002" +
    "\000\010\007\173\010\042\012\044\001\002\000\004\007" +
    "\172\001\002\000\004\005\ufff9\001\002\000\004\005\ufffb" +
    "\001\002\000\004\002\ufffd\001\002\000\004\005\200\001" +
    "\002\000\004\005\177\001\002\000\004\002\ufffc\001\002" +
    "\000\004\002\ufffe\001\002\000\004\023\202\001\002\000" +
    "\006\003\204\030\203\001\002\000\004\023\206\001\002" +
    "\000\004\023\205\001\002\000\004\024\uffe8\001\002\000" +
    "\004\024\uffe9\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\204\000\006\003\005\004\006\001\001\000\010\006" +
    "\011\007\013\010\014\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\005\174\001\001\000\004\005\025\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\011\027\012\030\013\032" +
    "\001\001\000\012\014\042\015\167\016\045\017\044\001" +
    "\001\000\002\001\001\000\012\014\042\015\040\016\045" +
    "\017\044\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\014\165\016\045\017\044\001\001\000" +
    "\006\024\144\025\143\001\001\000\002\001\001\000\006" +
    "\022\052\023\050\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\020\056\021\135\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\020\056\021" +
    "\055\001\001\000\006\026\064\027\063\001\001\000\002" +
    "\001\001\000\004\020\060\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\030\103\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\031\073\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\031\100\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\031\113\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\031\121" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\020\060\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\030\157\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\031" +
    "\155\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\014\165\016\045\017\044\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

	System.out.println("PARSERRIZZO...");
	symbol_table = new Hashtable<String,String>();

    }


 
	//variabili globali a livello di classe parser
	public static boolean flagError = false;
	public static String errMex = "";
	public static Hashtable<String,String> symbol_table;
	
	//Overriding delle funzioni per la gestione degli errori di CUP
	 public void report_error(String message, Object info) {
		StringBuffer m = new StringBuffer(message);
		if (info instanceof Symbol) {
			 if (((Symbol)info).left != 1 && ((Symbol)info).right != 1) {
				if (((Symbol)info).left != -1 && ((Symbol)info).right != -1) {
					int line = (((Symbol)info).left)+1;
					int column = (((Symbol)info).right)+1;
					m.append(" (linea "+line+", colonna "+column+")");
				}
			}
			System.err.println(m);
		}
	 }
	 public void syntax_error(Symbol cur_token){}

	//ritorna il valore semantico che cè all'interno dello stack ad una certa posizione, usato all'interno delle action delle regole CUP
	//utile quando devo recuperare il valore di un simbolo Terminale o Non Terminale annegato nello stack
	public Object stack(int position) { //NON USATA
			return (((Symbol)stack.elementAt(tos+position)).value);
	}
 

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


 
	int flagDebug = 0;
	private void stampa(String s, String tipo){ 
		if (flagDebug == 1){
			System.out.println(tipo+": "+ s);
		}else{
			if(tipo.equals("ERR")){
				parser.errMex = "ERR: "+s; //interessa solo se ci sono Errori, nient'altro
				parser.flagError = true;
				System.out.println(parser.errMex);
			}else{
				System.out.println(tipo+": "+ s);
			}
		}
	}

  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // content ::= STRINGA 
            {
              String RESULT = null;
		int strleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int strright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String str = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = new String(str); 
              CUP$parser$result = new java_cup.runtime.Symbol(22/*content*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // alfanum ::= TIMESTAMP 
            {
              String RESULT = null;
		int tempoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int temporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String tempo = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = new String(tempo); 
              CUP$parser$result = new java_cup.runtime.Symbol(23/*alfanum*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // alfanum ::= NUMERO 
            {
              String RESULT = null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String num = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = new String(num); 
              CUP$parser$result = new java_cup.runtime.Symbol(23/*alfanum*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // alfanum ::= STRINGA 
            {
              String RESULT = null;
		int strleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int strright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String str = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = new String(str); 
              CUP$parser$result = new java_cup.runtime.Symbol(23/*alfanum*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // attributi_item_list ::= ATTR_NAME UG APICI alfanum APICI 
            {
              String RESULT = null;
		int itemtipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int itemtiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String itemtipo = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				stampa("NAME="+itemtipo, "ATTR. ITEM");
				RESULT = new String(itemtipo);
			
              CUP$parser$result = new java_cup.runtime.Symbol(21/*attributi_item_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // attributi_item_list ::= ATTR_TIPO UG APICI alfanum APICI 
            {
              String RESULT = null;
		int itemtipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int itemtiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String itemtipo = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				stampa(" ITEMTIPO="+itemtipo, "ATTR. ITEM");
				RESULT = new String(itemtipo);
			
              CUP$parser$result = new java_cup.runtime.Symbol(21/*attributi_item_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // attributi_item_list ::= ATTR_NAME UG APICI alfanum APICI ATTR_VALUE UG APICI alfanum APICI 
            {
              String RESULT = null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				parser.symbol_table.put(name, value);
				stampa(" NAME="+name+" VALUE="+value,"ATTR. ITEM");
				RESULT = new String(name+":"+value);
			
              CUP$parser$result = new java_cup.runtime.Symbol(21/*attributi_item_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // attributi_item_list ::= ATTR_TIPO UG APICI STRINGA APICI ATTR_VALUE UG APICI alfanum APICI 
            {
              String RESULT = null;
		int itemtipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int itemtiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		String itemtipo = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				parser.symbol_table.put(itemtipo, value);
				stampa(" ITEMTIPO="+itemtipo+" VALUE="+value,"ATTR. ITEM");
				RESULT = new String(itemtipo+":"+value);
			
              CUP$parser$result = new java_cup.runtime.Symbol(21/*attributi_item_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // attributi_item ::= attributi_item_list PAR_ANG_C 
            {
              String RESULT = null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String attr = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				RESULT = new String(attr);
			
              CUP$parser$result = new java_cup.runtime.Symbol(20/*attributi_item*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // attributo_lista ::= ATTR_NAME UG APICI STRINGA APICI ATTR_TIMESTAMP UG APICI TIMESTAMP APICI 
            {
              String RESULT = null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int tempoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int temporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String tempo = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				parser.symbol_table.put("BUNDLE-NAME", name);
				parser.symbol_table.put("TIMESTAMP-"+name, tempo);
				RESULT = new String(name+":"+tempo);
			
              CUP$parser$result = new java_cup.runtime.Symbol(17/*attributo_lista*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // attributo_lista ::= ATTR_TIMESTAMP UG APICI TIMESTAMP APICI 
            {
              String RESULT = null;
		int tempoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int temporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String tempo = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				parser.symbol_table.put("TIMESTAMP", tempo);
				RESULT = new String(" TIMESTAMP="+tempo);
			
              CUP$parser$result = new java_cup.runtime.Symbol(17/*attributo_lista*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // attributi_lista ::= attributo_lista PAR_ANG_C 
            {
              String RESULT = null;
		int templeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tempright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String temp = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				stampa(temp,"ATTR. LISTA");
			
              CUP$parser$result = new java_cup.runtime.Symbol(16/*attributi_lista*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // attributi_proprieta_list ::= ATTR_NAME UG APICI STRINGA APICI 
            {
              String RESULT = null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
			parser.symbol_table.put(name, "yes");
			stampa(" NAME="+name+" VALUE=no-value","ATTR. PROPRIETA");
			RESULT = new String(name+":yes");
			
              CUP$parser$result = new java_cup.runtime.Symbol(19/*attributi_proprieta_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // attributi_proprieta_list ::= ATTR_NAME UG APICI STRINGA APICI ATTR_VALUE UG APICI alfanum APICI 
            {
              String RESULT = null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
			parser.symbol_table.put(name, value);
			stampa(" NAME="+name+" VALUE="+value,"ATTR. PROPRIETA");
			RESULT = new String(name+":"+value);
			
              CUP$parser$result = new java_cup.runtime.Symbol(19/*attributi_proprieta_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // attributi_proprieta ::= attributi_proprieta_list PAR_ANG_C 
            {
              String RESULT = null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String attr = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				RESULT = new String(attr);
			
              CUP$parser$result = new java_cup.runtime.Symbol(18/*attributi_proprieta*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // attributo_comando ::= ATTR_NAME UG APICI STRINGA APICI 
            {
              String RESULT = null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				parser.symbol_table.put("COMANDO-NAME", name);
				RESULT = new String(" NAME="+name);
			
              CUP$parser$result = new java_cup.runtime.Symbol(9/*attributo_comando*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // attributi_comando_list ::= attributo_comando 
            {
              String RESULT = null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String attr = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		RESULT = new String(attr); 
              CUP$parser$result = new java_cup.runtime.Symbol(8/*attributi_comando_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // attributi_comando ::= attributi_comando_list PAR_ANG_C 
            {
              String RESULT = null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String attr = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				stampa(attr,"ATTR. COMANDO");
			
              CUP$parser$result = new java_cup.runtime.Symbol(7/*attributi_comando*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // attributo_pwxml ::= ATTR_NAME UG APICI error APICI 
            {
              String RESULT = null;
		 
				stampa("NAME - formato errato", "ERR");
				RESULT = new String("");
			
              CUP$parser$result = new java_cup.runtime.Symbol(6/*attributo_pwxml*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // attributo_pwxml ::= ATTR_NAME UG APICI STRINGA APICI 
            {
              String RESULT = null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				parser.symbol_table.put("NAME", name);
				RESULT = new String(" NAME="+name);
			
              CUP$parser$result = new java_cup.runtime.Symbol(6/*attributo_pwxml*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // attributo_pwxml ::= ATTR_ID UG APICI error APICI 
            {
              String RESULT = null;
		 
				stampa("ID - formato errato", "ERR");
				RESULT = new String("");
			
              CUP$parser$result = new java_cup.runtime.Symbol(6/*attributo_pwxml*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // attributo_pwxml ::= ATTR_ID UG APICI NUMERO APICI 
            {
              String RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				parser.symbol_table.put("ID", id);
				RESULT = new String(" ID="+id);
			
              CUP$parser$result = new java_cup.runtime.Symbol(6/*attributo_pwxml*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // attributi_pwxml_list ::= attributo_pwxml 
            {
              String RESULT = null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String attr = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = new String(attr); 
              CUP$parser$result = new java_cup.runtime.Symbol(5/*attributi_pwxml_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // attributi_pwxml ::= attributi_pwxml_list PAR_ANG_C 
            {
              String RESULT = null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String attr = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
				stampa(attr,"ATTR. PWXML");
			
              CUP$parser$result = new java_cup.runtime.Symbol(4/*attributi_pwxml*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // item ::= ITEM_OPEN attributi_item_list DIV PAR_ANG_C 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(14/*item*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // item ::= ITEM_OPEN attributi_item content ITEM_CLOSE 
            {
              Object RESULT = null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String attr = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String body = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 	parser.symbol_table.put(attr, body); stampa(body,"BODY ITEM"); 
              CUP$parser$result = new java_cup.runtime.Symbol(14/*item*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // item_list ::= item_list item 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(15/*item_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // item_list ::= item 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(15/*item_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // lista ::= LISTA_OPEN attributi_lista error LISTA_CLOSE 
            {
              Object RESULT = null;
		 stampa("Check del body del tag LISTA", "ERR"); 
              CUP$parser$result = new java_cup.runtime.Symbol(13/*lista*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // lista ::= LISTA_OPEN error item_list LISTA_CLOSE 
            {
              Object RESULT = null;
		 stampa("Errore negli attributi del tag LISTA", "ERR"); 
              CUP$parser$result = new java_cup.runtime.Symbol(13/*lista*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // lista ::= LISTA_OPEN attributi_lista item_list LISTA_CLOSE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(13/*lista*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // proprieta ::= PROPRIETA_OPEN attributi_proprieta_list DIV PAR_ANG_C 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(12/*proprieta*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // proprieta ::= PROPRIETA_OPEN attributi_proprieta content PROPRIETA_CLOSE 
            {
              Object RESULT = null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String attr = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String body = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 parser.symbol_table.put(attr, body); stampa(body,"BODY PROPRIETA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(12/*proprieta*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // body_comando ::= lista 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*body_comando*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // body_comando ::= proprieta 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*body_comando*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // body_comando_list ::= body_comando_list body_comando 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(11/*body_comando_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // body_comando_list ::= body_comando 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(11/*body_comando_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // comandi ::= COMANDO_OPEN attributi_comando error COMANDO_CLOSE 
            {
              Object RESULT = null;
		 stampa("Check del body del tag COMANDO", "ERR"); 
              CUP$parser$result = new java_cup.runtime.Symbol(3/*comandi*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // comandi ::= COMANDO_OPEN error body_comando_list COMANDO_CLOSE 
            {
              Object RESULT = null;
		 stampa("Errore negli attributi del tag COMANDO", "ERR"); 
              CUP$parser$result = new java_cup.runtime.Symbol(3/*comandi*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // comandi ::= COMANDO_OPEN attributi_comando body_comando_list COMANDO_CLOSE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*comandi*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // pwxml ::= PWXML_OPEN attributi_pwxml error PWXML_CLOSE 
            {
              Object RESULT = null;
		 stampa("Check del body del tag PWXML", "ERR"); 
              CUP$parser$result = new java_cup.runtime.Symbol(2/*pwxml*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // pwxml ::= PWXML_OPEN error comandi PWXML_CLOSE 
            {
              Object RESULT = null;
		 stampa("Errore negli attributi del tag PWXML", "ERR"); 
              CUP$parser$result = new java_cup.runtime.Symbol(2/*pwxml*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // pwxml ::= PWXML_OPEN attributi_pwxml comandi PWXML_CLOSE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*pwxml*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // progr ::= error 
            {
              Object RESULT = null;
		 stampa("Controllare l'XML dal principio", "ERR"); 
              CUP$parser$result = new java_cup.runtime.Symbol(1/*progr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // progr ::= pwxml 
            {
              Object RESULT = null;
		 
				if( parser.flagError == false ){
					System.out.println("");
					stampa("errMex = \"empty\"  & flagError = "+parser.flagError,"INFO");
					stampa("FINE PARSER!", "INFO"); 
				}else{
					System.out.println("");
					stampa("errMex = \""+parser.errMex+"\"  & flagError = "+parser.flagError,"INFO");
					stampa("FINE PARSER - trovato errore!", "INFO"); 
				}
			
              CUP$parser$result = new java_cup.runtime.Symbol(1/*progr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= progr EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

