
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 28 17:58:45 CET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_ANG_C = 18;
  public static final int ATTR_NAME = 15;
  public static final int LISTA_CLOSE = 9;
  public static final int STRINGA = 23;
  public static final int PROPRIETA_CLOSE = 7;
  public static final int ATTR_TIPO = 16;
  public static final int ITEM_OPEN = 10;
  public static final int UG = 19;
  public static final int ATTR_ID = 14;
  public static final int COMANDO_OPEN = 4;
  public static final int EOF = 0;
  public static final int DIV = 20;
  public static final int APICI = 17;
  public static final int PWXML_OPEN = 2;
  public static final int NUMERO = 22;
  public static final int error = 1;
  public static final int ATTR_TIMESTAMP = 13;
  public static final int PWXML_CLOSE = 3;
  public static final int TIMESTAMP = 21;
  public static final int COMANDO_CLOSE = 5;
  public static final int PROPRIETA_OPEN = 6;
  public static final int LISTA_OPEN = 8;
  public static final int ITEM_CLOSE = 11;
  public static final int ATTR_VALUE = 12;
}

